### ISSUE TITLE
Please clarify dependency scope in pom.xml to avoid bringing in unnecessary libraries

### ISSUE THREAD

**Issue by jacek99** [flipkart-incubator/Lois#3]
In a corporate environent, we have to obtain legal clearance for every library, including all of its dependencies.

Your pom.xml brings in a lot of unnecesary test-only dependencies:

        
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8.8</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>2.9.1</version>
        </dependency>

both of these have a huge dependency graph (especially the last one).

Could you please add the Maven scope tag to each of them:

<scope>test</scope>

which should help avoid bringing both of them as a dependency when we just want to use Lois at runtime.

Thank you

**Comment by jacek99** [comment]
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by mrphoebs** [comment]
Changed testng scope to test and removed javadoc and cobertura dependencies from master branch

**Comment by jacek99** [comment]
I still see testng without any scope specified in the troot pom.xml



<dependency>
<groupId>org.testng</groupId>
<artifactId>testng</artifactId>
<version>6.8.8</version>
</dependency>

**Comment by mrphoebs** [comment]
Done

**Comment by jacek99** [comment]
thank you much appreciated. Any chance we could get a 1.1.3 release with  this on clojars? 

thank you once again. With only one dependency now this makes approval much easier for me.

**Comment by mrphoebs** [comment]
1.1.3 release done. Glad to hear that this makes it easier to use.
